# Spring Configuration
spring:
  application:
    name: @project.name@
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  "http://localhost:8081/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs"

# Swagger Documentation
swagger:
  service:
    version: "1.0.0"
    title: ${spring.application.name}
    description: "Skeleton app swagger"
